import os
from typing import Dict

import sendgrid
from sendgrid.helpers.mail import Email, Mail, Content, To
from agents import Agent, function_tool


@function_tool
def send_email(subject: str, html_body: str) -> Dict[str, str]:
    """Send an email with the given subject and HTML body."""
    sg = sendgrid.SendGridAPIClient(api_key=os.environ["SENDGRID_API_KEY"])
    from_email = Email(os.environ["EMAIL_FROM"])
    to_email = To(os.environ["EMAIL_TO"])
    content = Content("text/html", html_body)
    mail = Mail(from_email, to_email, subject, content).get()
    response = sg.client.mail.send.post(request_body=mail)
    print("Email response", response.status_code)
    return {"status": "success", "status_code": str(response.status_code)}


INSTRUCTIONS = """You are able to send a nicely formatted HTML email based on a detailed research report.
You will be provided with a markdown report. Convert it into clean, well-presented HTML and send it 
with an appropriate subject line that captures the essence of the report topic.

HTML formatting guidelines:
- Use a clean, readable font (Georgia or similar serif for body)
- Include a styled header with the report title
- Use proper heading hierarchy (h1, h2, h3)
- Style blockquotes and lists attractively
- Add a footer noting it was generated by Deep Researcher
- Max width 700px, centred, with generous padding"""

email_agent = Agent(
    name="EmailAgent",
    instructions=INSTRUCTIONS,
    tools=[send_email],
    model="gpt-4o-mini",
)
